### ISSUE TITLE
My homeassistant has just been upgraded to homeassistant core-2021.12.2

### ISSUE THREAD

**Issue by etmomoabc** [mKeRix/room-assistant#994]
**Describe the bug**
All ble can't be found
**To reproduce**
Steps required to reproduce the issue.

**Relevant logs**
error - undefined: Command failed: hciconfig hci0 reset

```text
```

**Relevant configuration**
# You don't need to add the MQTT details for Home Assistant with the add-on installation, it will be auto-discovered!
global:
  instanceName: Garage
  integrations:
    - homeAssistant
    - bluetoothLowEnergy
bluetoothLowEnergy:
  allowlist:
    - d546df97475747efbe093e2dcbdd0c77-1229-2278
  timeout: 4
  updateFrequency: 2

```yaml
```

**Expected behavior**

**Environment**
 - room-assistant version: 2.19.0
 - installation type: Hass.io
 - hardware: Raspberry Pi 4
 - OS: 

**Additional context**
In fact, the room assistant worked well before upgrading to homeassistant core-2021.12.2!

**Comment by BelgarionNL** [comment]
its because the value_template has changed in home assistant.

https://community.home-assistant.io/t/mqtt-error-after-update-to-2022-2/388204/6

so room-assistant needs an update I think.

**Comment by mKeRix** [comment]
room-assistant doesn't utilize the `value_template` setting anywhere in the code (from what I could find). I also keep my HA instance up-to-date and haven't seen any issues or warnings in the logs. If you still have this issue and can provide more info on how to reproduce feel comment here again and I'll re-open.

**Comment by bachoo786** [comment]
Hey @mKeRix 

I am having issues on my docker. Here are my logs: 
```
3/30/2022, 1:37:58 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://XXXX:1883
3/30/2022, 1:37:59 PM - info - NestApplication: Nest application successfully started
3/30/2022, 1:37:59 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral GBK_H61A0_6E44 with ID d4adfc1c6e44 and RSSI -28
3/30/2022, 1:38:00 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 4cecf82990bc
3/30/2022, 1:38:28 PM - error - BluetoothService: Failed to query value from 4cecf82990bc: timed out
3/30/2022, 1:38:31 PM - error - undefined: Command failed: hciconfig hci0 reset
3/30/2022, 1:38:43 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
3/30/2022, 1:38:51 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 4cecf82990bc
3/30/2022, 1:39:08 PM - info - BluetoothLowEnergyService: Discovered companion app with ID 410588B6-BCF9-47FD-ACE5-90E776F3A6C5 for tag 4cecf82990bc
3/30/2022, 1:39:30 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
3/30/2022, 1:39:33 PM - error - undefined: Command failed: hciconfig hci0 reset
3/30/2022, 1:39:45 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
3/30/2022, 1:40:48 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 518a34198602
3/30/2022, 1:41:00 PM - info - BluetoothLowEnergyService: Discovered companion app with ID 410588B6-BCF9-47FD-ACE5-90E776F3A6C5 for tag 518a34198602
3/30/2022, 1:41:30 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
```
Do you know why am I getting this error: `error - undefined: Command failed: hciconfig hci0 reset` ?

**Comment by bachoo786** [comment]
> Hey @mKeRix
> 
> I am having issues on my docker. Here are my logs:
> 
> ```
> 3/30/2022, 1:37:58 PM - info - HomeAssistantService: Successfully connected to MQTT broker at mqtt://XXXX:1883
> 3/30/2022, 1:37:59 PM - info - NestApplication: Nest application successfully started
> 3/30/2022, 1:37:59 PM - info - BluetoothLowEnergyService: Discovered nearby BLE peripheral GBK_H61A0_6E44 with ID d4adfc1c6e44 and RSSI -28
> 3/30/2022, 1:38:00 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 4cecf82990bc
> 3/30/2022, 1:38:28 PM - error - BluetoothService: Failed to query value from 4cecf82990bc: timed out
> 3/30/2022, 1:38:31 PM - error - undefined: Command failed: hciconfig hci0 reset
> 3/30/2022, 1:38:43 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
> 3/30/2022, 1:38:51 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 4cecf82990bc
> 3/30/2022, 1:39:08 PM - info - BluetoothLowEnergyService: Discovered companion app with ID 410588B6-BCF9-47FD-ACE5-90E776F3A6C5 for tag 4cecf82990bc
> 3/30/2022, 1:39:30 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
> 3/30/2022, 1:39:33 PM - error - undefined: Command failed: hciconfig hci0 reset
> 3/30/2022, 1:39:45 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
> 3/30/2022, 1:40:48 PM - info - BluetoothLowEnergyService: Attempting app discovery for tag 518a34198602
> 3/30/2022, 1:41:00 PM - info - BluetoothLowEnergyService: Discovered companion app with ID 410588B6-BCF9-47FD-ACE5-90E776F3A6C5 for tag 518a34198602
> 3/30/2022, 1:41:30 PM - warn - BluetoothService: Did not detect any low energy advertisements in a while, resetting
> ```
> 
> Do you know why am I getting this error: `error - undefined: Command failed: hciconfig hci0 reset` ?

@mKeRix can you please help? I am running RA on docker and keep on getting this error: 

`error - undefined: Command failed: hciconfig hci0 reset`

**Comment by JohnTranQUT** [comment]
@bachoo786

Try upgrading or downgrading the kernel. I've found reports of the kernel having Bluetooth Instability.

### Details
Not sure if this is a fix however I had installed a **Ubuntu 20.04 LTS VM** to circumvent this issue.
Attempted to install the HomeAssistant Supervisor version but it wasn't doing what I had wanted.
Instead, I went with installing only Room-Assistant on it by itself.

The same issue came up. The kernel of the Ubuntu installed was v 5.4 (found by running **`name -sr`**).

I've tried many different things but running **`dmesg`** reveals **debugfs** showing the entries:

> debugfs: File 'le_min_key_size' in directory 'hci0' already present!
debugfs: File 'le_max_key_size' in directory 'hci0' already present!
debugfs: File 'force_bredr_smp' in directory 'hci0' already present!


From reading https://bugzilla.kernel.org/show_bug.cgi?id=204765 , I've went ahead and installed the kernel v 5.6.
So far, only one error from **`dmsg`** shows up:
> debugfs: File 'force_bredr_smp' in directory 'hci0' already present!

The stability of the Bluetooth increased and the Room-Assistant no longer calls for the **bluetoothctl hci0 reset**.

**Comment by bachoo786** [comment]
> @bachoo786
> 
> Try upgrading or downgrading the kernel. I've found reports of the kernel having Bluetooth Instability.
> 
> ### Details
> Not sure if this is a fix however I had installed a **Ubuntu 20.04 LTS VM** to circumvent this issue. Attempted to install the HomeAssistant Supervisor version but it wasn't doing what I had wanted. Instead, I went with installing only Room-Assistant on it by itself.
> 
> The same issue came up. The kernel of the Ubuntu installed was v 5.4 (found by running **`name -sr`**).
> 
> I've tried many different things but running **`dmesg`** reveals **debugfs** showing the entries:
> 
> > debugfs: File 'le_min_key_size' in directory 'hci0' already present!
> > debugfs: File 'le_max_key_size' in directory 'hci0' already present!
> > debugfs: File 'force_bredr_smp' in directory 'hci0' already present!
> 
> From reading https://bugzilla.kernel.org/show_bug.cgi?id=204765 , I've went ahead and installed the kernel v 5.6. So far, only one error from **`dmsg`** shows up:
> 
> > debugfs: File 'force_bredr_smp' in directory 'hci0' already present!
> 
> The stability of the Bluetooth increased and the Room-Assistant no longer calls for the **bluetoothctl hci0 reset**.

I do not want to upgrade to kernel 5.6 as my zigbee stick had issues communicating.
