### ISSUE TITLE
Installation Issue - BLE

### ISSUE THREAD

**Issue by irose57** [mKeRix/room-assistant#71]
Hi.
Trying to install room-assistant but I'm getting the following error after start. Followed installation instructions so not sure what is causing it but the error seems to be 'ERROR raspberrypi-814/BROKER: Failed to load service '/home/pi/room-assistant/services/ble.service.js' { Error: Cannot find module 'bluetooth-hci-socket'

pi@raspberrypi:~/room-assistant $ npm start

> room-assistant@1.1.0 start /home/pi/room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: mqtt,ble
Packages needed: mqtt@2.18.8,noble@1.9.1
Already installed: mqtt@2.18.8,noble@1.9.1
Now installing: 
[2018-11-21T21:30:27.834Z] INFO  raspberrypi-814/BROKER: Moleculer v0.13.4 is starting...
[2018-11-21T21:30:27.892Z] INFO  raspberrypi-814/BROKER: Node ID: raspberrypi-814
[2018-11-21T21:30:27.899Z] INFO  raspberrypi-814/BROKER: Namespace: <not defined>
[2018-11-21T21:30:27.911Z] INFO  raspberrypi-814/REGISTRY: Strategy: RoundRobinStrategy
[2018-11-21T21:30:27.946Z] INFO  raspberrypi-814/BROKER: Serializer: JSONSerializer
[2018-11-21T21:30:27.967Z] INFO  raspberrypi-814/BROKER: Registered 10 internal middleware(s).
[2018-11-21T21:30:30.432Z] ERROR raspberrypi-814/BROKER: Failed to load service '/home/pi/room-assistant/services/ble.service.js' { Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/bindings.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:688:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32) code: 'MODULE_NOT_FOUND' }
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at ServiceBroker.getConstructorName (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1278:20)
    at ServiceBroker.normalizeSchemaConstructor (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1303:21)
    at ServiceBroker.loadService (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:540:17)
    at _.uniq.forEach.f (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:44)
    at Array.forEach (<anonymous>)
    at loadServices (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:24)
    at startBroker (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:422:2)
    at tryCatcher (/home/pi/room-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:17:14)

**Comment by mKeRix** [comment]
Hey there,
could you try running `npm install noble@1.9.1 --no-save --no-package-lock` from the room-assistant folder and send me the output of that command?

**Comment by irose57** [comment]
Hi - sorry for the late reply. I tried starting from scratch in case I'd made a mistake.
Steps where - Install jessie lite, install node.js (9.7.1), follow room-assistant install instructions (and config). I've tried this twice now and get to the following where it stalls.

pi@raspberrypi:~/room-assistant $ npm start

> room-assistant@1.1.0 start /home/pi/room-assistant
> bin/room-assistant-runner.js

Installing dependencies for: mqtt,ble
Packages needed: mqtt@2.18.8,noble@1.9.1
Already installed: 
Now installing: mqtt@2.18.8,noble@1.9.1
npm WARN notice [SECURITY] debug has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=debug&version=2.2.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.

> usb@1.5.0 install /home/pi/room-assistant/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v59-linux-arm.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@9.7.1 (node-v59 ABI, glibc) (falling back to source compile with node-gyp) 
make: Entering directory '/home/pi/room-assistant/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
  AR(target) Release/obj.target/usb.a
  COPY Release/usb.a
  CXX(target) Release/obj.target/usb_bindings/src/node_usb.o
../src/node_usb.cc: In function ‘void handleHotplug(std::pair<libusb_device*, libusb_hotplug_event>)’:
../src/node_usb.cc:151:58: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
  Nan::MakeCallback(Nan::New(hotplugThis), "emit", 2, argv);
                                                          ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/node_usb.cc:1:
../../nan/nan.h:1000:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/usb_bindings/src/device.o
../src/device.cc: In static member function ‘static void Req::default_after(uv_work_t*)’:
../src/device.cc:237:64: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
    Nan::MakeCallback(device, Nan::New(baton->callback), 1, argv);
                                                                ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/device.cc:1:
../../nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  CXX(target) Release/obj.target/usb_bindings/src/transfer.o
../src/transfer.cc: In function ‘void handleCompletion(Transfer*)’:
../src/transfer.cc:126:72: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(self->handle(), Nan::New(self->v8callback), 3, argv);
                                                                        ^
In file included from ../src/helpers.h:3:0,
                 from ../src/node_usb.h:21,
                 from ../src/transfer.cc:1:
../../nan/nan.h:958:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/usb_bindings.node
  COPY Release/usb_bindings.node
  COPY /home/pi/room-assistant/node_modules/usb/src/binding/usb_bindings.node
  TOUCH Release/obj.target/action_after_build.stamp
make: Leaving directory '/home/pi/room-assistant/node_modules/usb/build'

> bluetooth-hci-socket@0.5.1 install /home/pi/room-assistant/node_modules/bluetooth-hci-socket
> node-gyp rebuild

make: Entering directory '/home/pi/room-assistant/node_modules/bluetooth-hci-socket/build'
  CXX(target) Release/obj.target/binding/src/BluetoothHciSocket.o
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::poll()’:
../src/BluetoothHciSocket.cpp:251:95: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
     Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                               ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:979:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
../src/BluetoothHciSocket.cpp: In member function ‘void BluetoothHciSocket::emitErrnoError()’:
../src/BluetoothHciSocket.cpp:275:72: warning: ‘v8::Local<v8::Object> v8::Function::NewInstance(int, v8::Local<v8::Value>*) const’ is deprecated: Use maybe version [-Wdeprecated-declarations]
   Local<Value> error = errorConstructor->NewInstance(1, constructorArgs);
                                                                        ^
In file included from /home/pi/.node-gyp/9.7.1/include/node/v8.h:26:0,
                 from /home/pi/.node-gyp/9.7.1/include/node/node.h:63,
                 from /home/pi/.node-gyp/9.7.1/include/node/node_buffer.h:25,
                 from ../src/BluetoothHciSocket.cpp:7:
/home/pi/.node-gyp/9.7.1/include/node/v8.h:3894:31: note: declared here
                 Local<Object> NewInstance(int argc, Local<Value> argv[]) const);
                               ^
/home/pi/.node-gyp/9.7.1/include/node/v8config.h:318:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/BluetoothHciSocket.cpp:282:93: warning: ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated [-Wdeprecated-declarations]
   Nan::MakeCallback(Nan::New<Object>(this->This), Nan::New("emit").ToLocalChecked(), 2, argv);
                                                                                             ^
In file included from ../src/BluetoothHciSocket.cpp:8:0:
../../nan/nan.h:979:46: note: declared here
   NAN_DEPRECATED inline v8::Local<v8::Value> MakeCallback(
                                              ^~~~~~~~~~~~
  SOLINK_MODULE(target) Release/obj.target/binding.node
  COPY Release/binding.node
make: Leaving directory '/home/pi/room-assistant/node_modules/bluetooth-hci-socket/build'
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

+ mqtt@2.18.8
+ noble@1.9.1
added 111 packages in 279.8s
[2018-11-22T21:03:47.973Z] INFO  raspberrypi-1027/BROKER: Moleculer v0.13.4 is starting...
[2018-11-22T21:03:48.037Z] INFO  raspberrypi-1027/BROKER: Node ID: raspberrypi-1027
[2018-11-22T21:03:48.044Z] INFO  raspberrypi-1027/BROKER: Namespace: <not defined>
[2018-11-22T21:03:48.056Z] INFO  raspberrypi-1027/REGISTRY: Strategy: RoundRobinStrategy
[2018-11-22T21:03:48.110Z] INFO  raspberrypi-1027/BROKER: Serializer: JSONSerializer
[2018-11-22T21:03:48.146Z] INFO  raspberrypi-1027/BROKER: Registered 10 internal middleware(s).
[2018-11-22T21:03:51.178Z] INFO  raspberrypi-1027/REGISTRY: '$node' service is registered.
[2018-11-22T21:03:51.216Z] INFO  raspberrypi-1027/REGISTRY: 'mqtt' service is registered.
[2018-11-22T21:03:51.228Z] INFO  raspberrypi-1027/REGISTRY: 'ble' service is registered.
[2018-11-22T21:03:51.238Z] INFO  raspberrypi-1027/BROKER: ServiceBroker with 3 service(s) is started successfully.
[2018-11-22T21:03:51.443Z] INFO  raspberrypi-1027/MQTT: Connected to mqtt://192.168.0.122:1883
[            ......] - postinstall: sill install printInstalled

**Comment by irose57** [comment]
All working now. MQTT setting was wrong. Once I fixed that it started working.

**Comment by smeranda** [comment]
I too am getting the same error when I run `npm start`. I'm trying to load `"services": ["mqtt","ble"]`.

Error output:

```
ERROR garagepi-21620/BROKER: Failed to load service '/home/pi/room-assistant-package/room-assistant/services/ble.service.js' { Error: Cannot find module '../build/Release/binding.node'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant-package/room-assistant/node_modules/bluetooth-hci-socket/lib/native.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant-package/room-assistant/node_modules/bluetooth-hci-socket/index.js:8:20)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32) code: 'MODULE_NOT_FOUND' }
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at ServiceBroker.getConstructorName (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/src/service-broker.js:1278:20)
    at ServiceBroker.normalizeSchemaConstructor (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/src/service-broker.js:1303:21)
    at ServiceBroker.loadService (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/src/service-broker.js:540:17)
    at _.uniq.forEach.f (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:44)
    at Array.forEach (<anonymous>)
    at loadServices (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:24)
    at startBroker (/home/pi/room-assistant-package/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:422:2)
    at tryCatcher (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/room-assistant-package/room-assistant/node_modules/bluebird/js/release/async.js:17:14)
```

Here's the output when I run `npm install noble@1.9.1 --no-save --no-package-lock`. 

```
npm WARN moleculer-cron@0.0.2 requires a peer of moleculer@^0.11.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by mKeRix** [comment]
Could you try running `nom rebuild`?

In your case it seems like the ble dependency was not built correctly.

**Comment by smeranda** [comment]
@mKeRix, do you mean `npm rebuild`? I ran that and it blew up many more errors. 

It looks like I may need to have to go back to the drawing board on this one.

**Comment by smeranda** [comment]
So, I rebuilt my Raspberry Pi 2 with Raspbian. The only thing I installed was node (node 10.14.2 and npm 6.4.1) and then I followed your instructions for installing Room Assistant. Exact same issue.

```
ERROR garagepi-17168/BROKER: Failed to load service '/home/pi/room-assistant/services/ble.service.js' { Error: Cannot find module 'bluetooth-hci-socket'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/home/pi/room-assistant/node_modules/noble/lib/hci-socket/bindings.js:9:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32) code: 'MODULE_NOT_FOUND' }
Cannot read property 'prototype' of undefined TypeError: Cannot read property 'prototype' of undefined
    at ServiceBroker.getConstructorName (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1278:20)
    at ServiceBroker.normalizeSchemaConstructor (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:1303:21)
    at ServiceBroker.loadService (/home/pi/room-assistant/node_modules/moleculer/src/service-broker.js:540:17)
    at _.uniq.forEach.f (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:44)
    at Array.forEach (<anonymous>)
    at loadServices (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:352:24)
    at startBroker (/home/pi/room-assistant/node_modules/moleculer/bin/moleculer-runner.js:422:2)
    at tryCatcher (/home/pi/room-assistant/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/pi/room-assistant/node_modules/bluebird/js/release/promise.js:694:18)
    at _drainQueueStep (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:138:12)
    at _drainQueue (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:131:9)
    at Async._drainQueues (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/home/pi/room-assistant/node_modules/bluebird/js/release/async.js:17:14)
```

Any ideas?

**Comment by smeranda** [comment]
I should note, I tried node version 8.14 and 6.11.5, neither of which helped.

**Comment by smeranda** [comment]
Thanks for the reply. I ended up getting this to work on Raspberry Pi Zero with Node 8.9. However I can't get the service to work. I need to do some more digging.

**Comment by mKeRix** [comment]
Quick update: current version of room-assistant has fixed the Node 10 compatibility of the ble service!

**Comment by smeranda** [comment]
Awesome, I'll check it out!

**Comment by Blink515** [comment]
> Quick update: current version of room-assistant has fixed the Node 10 compatibility of the ble service!
@mKeRix 
This still appears to be an issue for me.  Node v10.15.0. NPM v6.4.1
I can send the full stack trace if needed.  This is on a new Pi Zero W that had no previous version of room-assistant.

` Failed to load service '/home/pi/room-assistant/services/ble.service.js' { Error: Cannot find module '@abandonware/bluetooth-hci-socket'
`

**Comment by mKeRix** [comment]
@Blink515 Did you already install the dependencies for the Bluetooth stuff as mentioned in the README? If not run the following commands from the room-assistant folder:

```bash
sudo apt-get install bluetooth bluez libbluetooth-dev libudev-dev libusb-1.0-0-dev
npm install --production
sudo setcap cap_net_raw+eip $(eval readlink -f `which node`)
npm start
```

Otherwise I would need to see the install log of the bluetooth module to know what is going on.

**Comment by gmalbert** [comment]
> Hey there,
> 
> sorry for not replying for so long - holiday season is always a busy time for me. I should note that the Bluetooth dependency is currently a bit broken on Node 10, people have submitted a fix but it has not been accepted yet. I've been following a thread where they're trying to fix this in another way and will update room-assistant accordingly once that is finalized.
> 
> But to solve your problem: could you please run the following commands in the room-assistant folder and send me the complete output?
> 
> ```
> rm -Rf node_modules/
> npm install noble@1.9.1 --no-save --no-package-lock
> ```
> This dependency must have an issue during build time, leading to the errors you posted when running.

I did this and got the following errors with the same issue noted above (I can't win!):


```
> usb@1.5.0 install /home/pi/room-assistant/node_modules/usb
> node-pre-gyp install --fallback-to-build

node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Tried to download(404): https://github.com/tessel/node-usb/releases/download/1.5.0/usb_bindings-v1.5.0-node-v64-linux-arm.tar.gz
node-pre-gyp WARN Pre-built binaries not found for usb@1.5.0 and node@10.15.0 (node-v64 ABI, glibc) (falling back to source compile with node-gyp)
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/room-assistant/node_modules/usb/build'
gyp ERR! System Linux 4.14.79+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "--fallback-to-build" "--module=/home/pi/room-assistant/node_modules/usb/src/binding/usb_bindings.node" "--module_name=usb_bindings" "--module_path=/home/pi/room-assistant/node_modules/usb/src/binding" "--napi_version=3" "--node_abi_napi=napi" "--napi_build_version=0" "--node_napi_label=node-v64"
gyp ERR! cwd /home/pi/room-assistant/node_modules/usb
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/room-assistant/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/room-assistant/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (/home/pi/room-assistant/node_modules/node-pre-gyp/lib/util/compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)
node-pre-gyp ERR! System Linux 4.14.79+
node-pre-gyp ERR! command "/opt/nodejs/bin/node" "/home/pi/room-assistant/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /home/pi/room-assistant/node_modules/usb
node-pre-gyp ERR! node -v v10.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.11.0
node-pre-gyp ERR! not ok
Failed to execute '/opt/nodejs/bin/node /opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js configure --fallback-to-build --module=/home/pi/room-assistant/node_modules/usb/src/binding/usb_bindings.node --module_name=usb_bindings --module_path=/home/pi/room-assistant/node_modules/usb/src/binding --napi_version=3 --node_abi_napi=napi --napi_build_version=0 --node_napi_label=node-v64' (1)
> bluetooth-hci-socket@0.5.1 install /home/pi/room-assistant/node_modules/bluetooth-hci-socket
> node-gyp rebuild

gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/10.15.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/tmp/.node-gyp"
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/home/pi/room-assistant/node_modules/bluetooth-hci-socket/build'
gyp ERR! System Linux 4.14.79+
gyp ERR! command "/opt/nodejs/bin/node" "/opt/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/pi/room-assistant/node_modules/bluetooth-hci-socket
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: xpc-connection@0.1.4 (node_modules/xpc-connection):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for xpc-connection@0.1.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 (node_modules/usb):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: usb@1.5.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 (node_modules/bluetooth-hci-socket):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bluetooth-hci-socket@0.5.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ noble@1.9.1
added 4 packages from 4 contributors in 63.67s
found 0 vulnerabilities
```

**Comment by mKeRix** [comment]
The error you posted is because of permission issues again, you shouldn't (need to) run the installation commands as root. These permission issues are usually fixed by deleting the `node_modules` directory and running the `npm install --production` command as a normal user, e.g. `pi`.

**Comment by jrtaaffe** [comment]
I'm also having installation issues.  

Feb 13 06:32:19 raspberrypi npm[3118]: Now installing: mqtt@2.18.8,@abandonware/noble@1.9.2-1,onoff@3.2.2,d6t@0.0.5,moleculer-prometheus@0.2.0
Feb 13 06:32:19 raspberrypi npm[3118]: { Error: Method Not Allowed
Feb 13 06:32:19 raspberrypi npm[3118]:     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
Feb 13 06:32:19 raspberrypi npm[3118]:     at /usr/share/npm/lib/cache/add-named.js:120:12
Feb 13 06:32:19 raspberrypi npm[3118]:     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
Feb 13 06:32:19 raspberrypi npm[3118]:     at FSReqWrap.oncomplete (fs.js:135:15)
Feb 13 06:32:19 raspberrypi npm[3118]:   statusCode: 405,
Feb 13 06:32:19 raspberrypi npm[3118]:   code: 'E405',
Feb 13 06:32:19 raspberrypi npm[3118]:   pkgid: 'abandonware/noble',
Feb 13 06:32:19 raspberrypi npm[3118]:   parent: 'room-assistant' }

Seems like permissions issues, but running as root produces them also...

**Comment by mar005** [comment]
I ran into this issue using the docker-compose method. I am now trying it on bare metal, but would like to use docker-compose. Any suggestions on how to fix the ble not found?
